//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int prestamoID { get; set; }
        public int clienteID { get; set; }
        public int peliculaID { get; set; }
        public System.DateTime fechaPrestamo { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<bool> devuelto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Peliculas Peliculas { get; set; }
    }
}
